//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdibahceCalismaCizelge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antre
    {
        public int Id { get; set; }
        public string PersonelAdSoyad { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> BirinciGiris { get; set; }
        public Nullable<System.TimeSpan> BirinciCikis { get; set; }
        public Nullable<System.TimeSpan> İkinciGiris { get; set; }
        public Nullable<System.TimeSpan> İkinciCikis { get; set; }
        public Nullable<System.TimeSpan> Fark { get; set; }
    }
}
