//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdibahceCalismaCizelge
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Personel_ID { get; set; }
        public string PersonelAdSoyad { get; set; }
        public System.DateTime PersonelGirisTarihi { get; set; }
        public Nullable<double> PersonelMaas { get; set; }
        public Nullable<double> PersonelMesaiSaat { get; set; }
    }
}
