//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdibahceCalismaCizelge
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Shift
    {
        [DisplayName("ID")]
        public int Shift_ID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        [DisplayName("Yýl ")]
        public int Yil_ID { get; set; }
        [DisplayName("Ay")]
        public int Ay_ID { get; set; }
        [DisplayName("Gün")]
        public int Gun_ID { get; set; }
        public bool Antre { get; set; }
        [DisplayName("Ýsim")]
        public string PersonelAdSoyad { get; set; }
        [DisplayName("Giriþ")]
        public Nullable<System.TimeSpan> GirisSaati { get; set; }
        [DisplayName("Çýkýþ")]
        public Nullable<System.TimeSpan> CikisSaati { get; set; }
        public Nullable<System.TimeSpan> Fark { get; set; }
        [DisplayName("Ýzin")]
        public bool Izinli { get; set; }
        public bool Yok { get; set; }
        public bool Raporlu { get; set; }
    }
}
